let courseData = [
  {
    campus: "Post Graduate",
    course: "MBA",
    specialization: "Finance",
    keyWord: "PGMBAF",
  },
  {
    campus: "Post Graduate",
    course: "MBA",
    specialization: "Marketing",
    keyWord: "PGMBAM",
  },
  {
    campus: "Post Graduate",
    course: "MBA",
    specialization: "Human Resource Management",
    keyWord: "PGMBAHRM",
  },
  {
    campus: "Post Graduate",
    course: "Ex - MBA",
    specialization: "Ex- MBA",
    keyWord: "PGEMBA",
  },
  {
    campus: "Post Graduate",
    course: "Ex - MBA",
    specialization: "Operation Management",
    keyWord: "PGEMBAOM",
  },
  {
    campus: "Post Graduate",
    course: "Life and Allied Sciences",
    specialization: "M.Sc Medical Lab Technology",
    keyWord: "PGLAMLT",
  },
  {
    campus: "Post Graduate",
    course: "M.Tech",
    specialization: "M.Tech",
    keyWord: "PGMT",
  },
  {
    campus: "Post Graduate",
    course: "M.Tech",
    specialization: "Mechatronics Engineering",
    keyWord: "PGMTMECHATRO",
  },
  {
    campus: "Post Graduate",
    course: "M.Tech",
    specialization: "Mechanical Engineering",
    keyWord: "PGMTME",
  },
  {
    campus: "Post Graduate",
    course: "M.Tech",
    specialization: "Electrical Engineering",
    keyWord: "PGMTEE",
  },
  {
    campus: "Post Graduate",
    course: "M.Tech",
    specialization: "Computer Science & Engineering",
    keyWord: "PGMTCSE",
  },
  {
    campus: "Post Graduate",
    course: "M.Tech",
    specialization: "Civil Engineering",
    keyWord: "PGMTCE",
  },
  {
    campus: "Post Graduate",
    course: "Applied Sciences",
    specialization: "M.Sc . Industrial Chemistry",
    keyWord: "PGASMIC",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "Int B.Tech -Mechanical Engineering",
    keyWord: "GEINTBTECHME",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "Int B.Tech - Mechatronics Engineering",
    keyWord: "GEINTBTECHMECHA",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "Int B.Tech - Computer Science Engineering",
    keyWord: "GEINTBTECHCSE",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "Int B.Tech - Civil Engineering",
    keyWord: "GEINTBTECHCE",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "B.Tech - Mechanical Engineering",
    keyWord: "GEBTECHME",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "B.Tech -Mechatronics Engineering",
    keyWord: "GEBTECHMECHA",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "B.Tech - Computer Science Engineering (CTIS)",
    keyWord: "GEBTECHCSECTIS",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "B.Tech - Computer Science Engineering (DS)",
    keyWord: "GEBTECHCSEDS",
  },
  {
    campus: "Graduate",
    course: "Engineering",
    specialization: "B.Tech - Civil Engineering",
    keyWord: "GEBTECHCE",
  },
  {
    campus: "Graduate",
    course: "Commerce and Management",
    specialization: "BBA",
    keyWord: "GCMBBA",
  },
  {
    campus: "Graduate",
    course: "Commerce and Management",
    specialization: "BBA - Financial Services",
    keyWord: "GCMBBAFS",
  },
  {
    campus: "Graduate",
    course: "BCA",
    specialization: "BCA",
    keyWord: "GBCA",
  },
  {
    campus: "Graduate",
    course: "B.IHTM",
    specialization: "B.IHTM",
    keyWord: "GBIHTM",
  },
  {
    campus: "Graduate",
    course: "Applied Sciences",
    specialization: "B.Sc Industrial Chemistry",
    keyWord: "GASBIC",
  },
  {
    campus: "Graduate",
    course: "Life and Allied Sciences",
    specialization: "B.Sc Medical Lab Technology",
    keyWord: "GLABMLT",
  },
  {
    campus: "Graduate",
    course: "Life and Allied Sciences",
    specialization: "B. Optometry",
    keyWord: "GLABOP",
  },
  {
    campus: "Graduate",
    course: "Life and Allied Sciences",
    specialization: "BSC Microbiology",
    keyWord: "GLABMB",
  },
  {
    campus: "Ph.D",
    course: "Ph.D",
    specialization: "Faculty of Engineering and Technology",
    keyWord: "PHDEAT",
  },
  {
    campus: "Ph.D",
    course: "Ph.D",
    specialization: "Faculty of Management,Economics & Commerce",
    keyWord: "PHDMEC",
  },
  {
    campus: "Ph.D",
    course: "Ph.D",
    specialization: "Faculty of Life , Health and Allied Sciences",
    keyWord: "PHDHA",
  },
  {
    campus: "Certificate Course",
    course: "Bar Operations",
    specialization: null,
    keyWord: "CCBAR",
  },
  {
    campus: "Certificate Course",
    course: "Barista",
    specialization: null,
    keyWord: "CCBARISTA",
  },
  {
    campus: "Certificate Course",
    course: "International Air Transport Association [IATA]",
    specialization: null,
    keyWord: "CCIATA",
  },
];

export default courseData;
